version: '3.8'

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/client/node_modules
      - ./client:/app/client
    ports:
      - 3000:3000
    command: npm start
    depends_on:
      - server
    restart: always
    environment:
      - DEBUG=False

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    volumes:
      - /app/server/node_modules
      - ./server:/app/server
    ports:
      - 5000:5000
    command: npm start
    restart: always
    environment:
      - DEBUG=False
